[custom.all.pack]
type   = "local"
path   = "."
ipkg   = "pack.ipkg"

[custom.all.pack-admin]
type   = "local"
path   = "."
ipkg   = "pack-admin.ipkg"

[custom.all.micropack]
type   = "local"
path   = "."
ipkg   = "micropack.ipkg"

[custom.all.parser]
type   = "git"
url    = "https://github.com/stefan-hoeck/idris2-parser"
commit = "latest:main"
ipkg   = "parser.ipkg"

[custom.all.parser-show]
type   = "git"
url    = "https://github.com/stefan-hoeck/idris2-parser"
commit = "latest:main"
ipkg   = "show/parser-show.ipkg"

[custom.all.parser-toml]
type   = "git"
url    = "https://github.com/stefan-hoeck/idris2-parser"
commit = "latest:main"
ipkg   = "toml/parser-toml.ipkg"
