[custom.all.pack]
type   = "local"
path   = "."
ipkg   = "pack.ipkg"

[custom.all.pack-admin]
type   = "local"
path   = "."
ipkg   = "pack-admin.ipkg"

[custom.all.micropack]
type   = "local"
path   = "."
ipkg   = "micropack.ipkg"

[custom.all.ilex]
type   = "git"
url    = "https://github.com/stefan-hoeck/idris2-ilex"
commit = "latest:main"
ipkg   = "ilex.ipkg"

[custom.all.ilex-toml]
type   = "git"
url    = "https://github.com/stefan-hoeck/idris2-ilex"
commit = "latest:main"
ipkg   = "toml/ilex-toml.ipkg"
